{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/23/comments/43692895.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/23#comment-43692895"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/23.json"}}, "type": "issue", "id": 23, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "mzML XML \"huge text node\" error"}, "content": {"raw": "Great! This seems to be working on the same large mzML files that were previously causing the error. Thanks again.", "markup": "markdown", "html": "<p>Great! This seems to be working on the same large mzML files that were previously causing the error. Thanks again.</p>", "type": "rendered"}, "created_on": "2018-03-04T16:29:43.671181+00:00", "user": {"display_name": "jacobrosenstein", "uuid": "{15b69590-5316-43cf-92b2-426db558db61}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B15b69590-5316-43cf-92b2-426db558db61%7D"}, "html": {"href": "https://bitbucket.org/%7B15b69590-5316-43cf-92b2-426db558db61%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/d3c71a487a958950c1466398730b1f58d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJ-4.png"}}, "nickname": "jacobrosenstein", "type": "user", "account_id": "5a9095b90e69ba52f30623f3"}, "updated_on": null, "type": "issue_comment", "id": 43692895}