{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5/comments/6034714.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/5#comment-6034714"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5.json"}}, "type": "issue", "id": 5, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "crash of AMDx64 installer"}, "content": {"raw": "Hi Achim,\n\nthanks for the feedback. I'm trying to figure this out, but not sure where to look right now. The installer works on the only Win7 x64 machine we can try it on at the moment, and it also has Python 2.7.5 installed.\n\nDoes the problem only occur with the latest version of the installer? I added the previous one back on the PyPI page.\n\n[Here](http://stackoverflow.com/a/14339295/1258041) is another thing we can try to diagnose this (we'll try it with your dump file here).", "markup": "markdown", "html": "<p>Hi Achim,</p>\n<p>thanks for the feedback. I'm trying to figure this out, but not sure where to look right now. The installer works on the only Win7 x64 machine we can try it on at the moment, and it also has Python 2.7.5 installed.</p>\n<p>Does the problem only occur with the latest version of the installer? I added the previous one back on the PyPI page.</p>\n<p><a data-is-external-link=\"true\" href=\"http://stackoverflow.com/a/14339295/1258041\" rel=\"nofollow\">Here</a> is another thing we can try to diagnose this (we'll try it with your dump file here).</p>", "type": "rendered"}, "created_on": "2013-09-12T14:03:31.514717+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": "2013-09-12T14:04:25.520685+00:00", "type": "issue_comment", "id": 6034714}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5/comments/6037016.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/5#comment-6037016"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5.json"}}, "type": "issue", "id": 5, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "crash of AMDx64 installer"}, "content": {"raw": "Hi Lev, \n\nI have tried the previous version of the installer - cannot get it to install either. \n\nNow downloading the debugging tools - will have a look a this again tomorrow to see.\n\nSpecs of my computer and version of python:\nIntel Core2 Duo E8500, 8 GByte RAM, Win7 SP1\nPython 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32\n\nMany thanks, \nAchim\n", "markup": "markdown", "html": "<p>Hi Lev, </p>\n<p>I have tried the previous version of the installer - cannot get it to install either. </p>\n<p>Now downloading the debugging tools - will have a look a this again tomorrow to see.</p>\n<p>Specs of my computer and version of python:\nIntel Core2 Duo E8500, 8 GByte RAM, Win7 SP1\nPython 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32</p>\n<p>Many thanks, \nAchim</p>", "type": "rendered"}, "created_on": "2013-09-12T16:25:29.677726+00:00", "user": {"display_name": "Achim Treumann", "uuid": "{fe720f14-c6f4-4796-90b1-bb204bcaa725}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bfe720f14-c6f4-4796-90b1-bb204bcaa725%7D"}, "html": {"href": "https://bitbucket.org/%7Bfe720f14-c6f4-4796-90b1-bb204bcaa725%7D/"}, "avatar": {"href": "https://bitbucket.org/account/achimt/avatar/"}}, "nickname": "achimt", "type": "user", "account_id": null}, "updated_on": null, "type": "issue_comment", "id": 6037016}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5/comments/6039932.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/5#comment-6039932"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5.json"}}, "type": "issue", "id": 5, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "crash of AMDx64 installer"}, "content": {"raw": "I tried the installer on another Win7 x64 machine, with an older Python 2.7.2, and it also worked.\n\nThe output I managed to get from the debugger doesn't help me that much: http://pastebin.com/AUQtfjYF\n\nTo be on the safe side: can you verify that your Python folder is writeable? Seems to be unrelated, but this was mentioned as a possible cause of problems with distutils-built installers on Windows in some of the search results I got.", "markup": "markdown", "html": "<p>I tried the installer on another Win7 x64 machine, with an older Python 2.7.2, and it also worked.</p>\n<p>The output I managed to get from the debugger doesn't help me that much: <a href=\"http://pastebin.com/AUQtfjYF\" rel=\"nofollow\" class=\"ap-connect-link\">http://pastebin.com/AUQtfjYF</a></p>\n<p>To be on the safe side: can you verify that your Python folder is writeable? Seems to be unrelated, but this was mentioned as a possible cause of problems with distutils-built installers on Windows in some of the search results I got.</p>", "type": "rendered"}, "created_on": "2013-09-12T20:06:48.572030+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": "2013-09-12T21:20:13.285470+00:00", "type": "issue_comment", "id": 6039932}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5/comments/6053643.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/5#comment-6053643"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5.json"}}, "type": "issue", "id": 5, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "crash of AMDx64 installer"}, "content": {"raw": "Also, did you use these installers before on this machine? If so, can you try a version that you know worked to see if it still does (if the 2.1.5 is not such a version)?\n\nIn the meantime, you can install from source via `pip`. ", "markup": "markdown", "html": "<p>Also, did you use these installers before on this machine? If so, can you try a version that you know worked to see if it still does (if the 2.1.5 is not such a version)?</p>\n<p>In the meantime, you can install from source via <code>pip</code>. </p>", "type": "rendered"}, "created_on": "2013-09-13T19:19:42.339433+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 6053643}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5/comments/6079425.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/5#comment-6079425"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5.json"}}, "type": "issue", "id": 5, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "crash of AMDx64 installer"}, "content": {"raw": "Hi Lev, \n\nthe pip install did work - I have pyteomics running on my Win7 machine now. \n\nPlease let me know, if you would like me to check anything on the installer.\n\nMany thanks, \nAchim", "markup": "markdown", "html": "<p>Hi Lev, </p>\n<p>the pip install did work - I have pyteomics running on my Win7 machine now. </p>\n<p>Please let me know, if you would like me to check anything on the installer.</p>\n<p>Many thanks, \nAchim</p>", "type": "rendered"}, "created_on": "2013-09-16T13:28:23.399233+00:00", "user": {"display_name": "Achim Treumann", "uuid": "{fe720f14-c6f4-4796-90b1-bb204bcaa725}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bfe720f14-c6f4-4796-90b1-bb204bcaa725%7D"}, "html": {"href": "https://bitbucket.org/%7Bfe720f14-c6f4-4796-90b1-bb204bcaa725%7D/"}, "avatar": {"href": "https://bitbucket.org/account/achimt/avatar/"}}, "nickname": "achimt", "type": "user", "account_id": null}, "updated_on": null, "type": "issue_comment", "id": 6079425}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5/comments/6080450.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/5#comment-6080450"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5.json"}}, "type": "issue", "id": 5, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "crash of AMDx64 installer"}, "content": {"raw": "Hi Achim,\n\nthanks for checking back. I asked a couple of questions in the two comments above; they can clarify if the problem is with your installation or with the installer files. Also I built another installer executable with the newest distutils, you can try running that one: [PyPI](https://pypi.python.org/packages/2.7/p/pyteomics/pyteomics-2.1.6.win-amd64_py2.7.5.exe#md5=7e4c4d3bdaa440b8883cd19a74cee493). Would be interesting to know if it crashes or not on your machine (works fine here).\n\nRegards, Lev", "markup": "markdown", "html": "<p>Hi Achim,</p>\n<p>thanks for checking back. I asked a couple of questions in the two comments above; they can clarify if the problem is with your installation or with the installer files. Also I built another installer executable with the newest distutils, you can try running that one: <a data-is-external-link=\"true\" href=\"https://pypi.python.org/packages/2.7/p/pyteomics/pyteomics-2.1.6.win-amd64_py2.7.5.exe#md5=7e4c4d3bdaa440b8883cd19a74cee493\" rel=\"nofollow\">PyPI</a>. Would be interesting to know if it crashes or not on your machine (works fine here).</p>\n<p>Regards, Lev</p>", "type": "rendered"}, "created_on": "2013-09-16T14:32:30.503104+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": "2013-09-17T09:37:33.885868+00:00", "type": "issue_comment", "id": 6080450}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5/comments/7387547.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/5#comment-7387547"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5.json"}}, "type": "issue", "id": 5, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "crash of AMDx64 installer"}, "content": {"raw": "I'll be happy to get back to this if the requested details or new info are available.", "markup": "markdown", "html": "<p>I'll be happy to get back to this if the requested details or new info are available.</p>", "type": "rendered"}, "created_on": "2013-12-17T12:51:33.239262+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 7387547}], "page": 1, "size": 7}