{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "links": {"attachments": {"href": "data/repositories/levitsky/pyteomics/issues/23/attachments_page=1.json"}, "self": {"href": "data/repositories/levitsky/pyteomics/issues/23.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/levitsky/pyteomics/issues/23/watch"}, "comments": {"href": "data/repositories/levitsky/pyteomics/issues/23/comments_page=1.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/23/mzml-xml-huge-text-node-error"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/levitsky/pyteomics/issues/23/vote"}}, "reporter": {"display_name": "jacobrosenstein", "uuid": "{15b69590-5316-43cf-92b2-426db558db61}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B15b69590-5316-43cf-92b2-426db558db61%7D"}, "html": {"href": "https://bitbucket.org/%7B15b69590-5316-43cf-92b2-426db558db61%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/d3c71a487a958950c1466398730b1f58d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJ-4.png"}}, "nickname": "jacobrosenstein", "type": "user", "account_id": "5a9095b90e69ba52f30623f3"}, "title": "mzML XML \"huge text node\" error", "component": null, "votes": 0, "watches": 1, "content": {"raw": "I am reading some large mzML files, and I am frequently seeing this error:\r\n\r\nXMLSyntaxError: xmlSAX2Characters: huge text node\r\n\r\nI have temporarily gone through mzml.py and xml.py and added the parameter huge_tree=True to all etree.iterparse() methods. This seems to have temporarily fixed it.", "markup": "markdown", "html": "<p>I am reading some large mzML files, and I am frequently seeing this error:</p>\n<p>XMLSyntaxError: xmlSAX2Characters: huge text node</p>\n<p>I have temporarily gone through mzml.py and xml.py and added the parameter huge_tree=True to all etree.iterparse() methods. This seems to have temporarily fixed it.</p>", "type": "rendered"}, "assignee": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2018-03-01T22:50:33.469631+00:00", "milestone": null, "updated_on": "2018-03-04T17:10:45.443619+00:00", "type": "issue", "id": 23}