{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "links": {"attachments": {"href": "data/repositories/levitsky/pyteomics/issues/27/attachments_page=1.json"}, "self": {"href": "data/repositories/levitsky/pyteomics/issues/27.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/levitsky/pyteomics/issues/27/watch"}, "comments": {"href": "data/repositories/levitsky/pyteomics/issues/27/comments_page=1.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/27/xml_retrieve_refs-is-undefined"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/levitsky/pyteomics/issues/27/vote"}}, "reporter": {"display_name": "Joshua Klein", "uuid": "{919f0add-304d-4b9a-8889-d2622a3dbc96}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B919f0add-304d-4b9a-8889-d2622a3dbc96%7D"}, "html": {"href": "https://bitbucket.org/%7B919f0add-304d-4b9a-8889-d2622a3dbc96%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/7d0e70bc74f783efa621a2bdd228ca22d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJK-3.png"}}, "nickname": "mobiusklein", "type": "user", "account_id": "557058:ff82222f-afe5-4135-a1b7-8de99a00f669"}, "title": "`XML._retrieve_refs` is undefined", "component": null, "votes": 0, "watches": 1, "content": {"raw": "In the base class for `XML`, there is a block at [line 381](#!/levitsky/pyteomics/src/bb94d1353d72604e635db1299910f767a02227a4/pyteomics/xml.py?at=default#xml.py-381) that calls a method called `_retrieve_refs`. This method isn't defined on `XML`, only on the `MzIdentML` subclass`. \r\n\r\nI'll open a PR shortly to fix the issue.", "markup": "markdown", "html": "<p>In the base class for <code>XML</code>, there is a block at <a data-is-external-link=\"true\" href=\"#!/levitsky/pyteomics/src/bb94d1353d72604e635db1299910f767a02227a4/pyteomics/xml.py?at=default#xml.py-381\" rel=\"nofollow\">line 381</a> that calls a method called <code>_retrieve_refs</code>. This method isn't defined on <code>XML</code>, only on the <code>MzIdentML</code> subclass`. </p>\n<p>I'll open a PR shortly to fix the issue.</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2018-05-21T13:47:44.963239+00:00", "milestone": null, "updated_on": "2018-05-21T15:16:37.157310+00:00", "type": "issue", "id": 27}