{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/49/comments/55808515.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/49#comment-55808515"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/49.json"}}, "type": "issue", "id": 49, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "mzidentml wrong annotation in DataFrame"}, "content": {"raw": "I will try again here.", "markup": "markdown", "html": "<p>I will try again here.</p>", "type": "rendered"}, "created_on": "2020-01-21T20:32:48.876416+00:00", "user": {"display_name": "Yasset Perez", "uuid": "{65732fe2-6047-4cf9-bbd0-6b71db8c6bb1}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B65732fe2-6047-4cf9-bbd0-6b71db8c6bb1%7D"}, "html": {"href": "https://bitbucket.org/%7B65732fe2-6047-4cf9-bbd0-6b71db8c6bb1%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/5626cfe6897dc495b83bc9eb61a3f22ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsYP-1.png"}}, "nickname": "Yasset Perez-Riverol", "type": "user", "account_id": "557058:bafc7224-b2a9-46b1-9918-153a342c1455"}, "updated_on": null, "type": "issue_comment", "id": 55808515}