{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47/comments/54483653.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/47#comment-54483653"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47.json"}}, "type": "issue", "id": 47, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "non-ascii characters in AuditCollection lead to UnicodeEncodeError"}, "content": {"raw": "A version of the suggested fix is applied in 80bb804 \\(with a version check\\), but we need to look around for more corner cases.\n\n\u200c", "markup": "markdown", "html": "<p>A version of the suggested fix is applied in <a href=\"#!/levitsky/pyteomics/commits/80bb804\" rel=\"nofollow\" class=\"ap-connect-link\">80bb804</a> (with a version check), but we need to look around for more corner cases.</p>\n<p>\u200c</p>", "type": "rendered"}, "created_on": "2019-10-22T15:08:34.372183+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 54483653}