{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/34/comments/48913383.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/34#comment-48913383"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/34.json"}}, "type": "issue", "id": 34, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "parser fails on numbers in modX sequence"}, "content": {"raw": "I've merged the requested changes into `pyteomics.cythonize` and uploaded a new release to PyPI.", "markup": "markdown", "html": "<p>I've merged the requested changes into <code>pyteomics.cythonize</code> and uploaded a new release to PyPI.</p>", "type": "rendered"}, "created_on": "2018-11-13T17:50:57.363004+00:00", "user": {"display_name": "Joshua Klein", "uuid": "{919f0add-304d-4b9a-8889-d2622a3dbc96}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B919f0add-304d-4b9a-8889-d2622a3dbc96%7D"}, "html": {"href": "https://bitbucket.org/%7B919f0add-304d-4b9a-8889-d2622a3dbc96%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/7d0e70bc74f783efa621a2bdd228ca22d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJK-3.png"}}, "nickname": "mobiusklein", "type": "user", "account_id": "557058:ff82222f-afe5-4135-a1b7-8de99a00f669"}, "updated_on": null, "type": "issue_comment", "id": 48913383}