{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/26/comments/45343727.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/26#comment-45343727"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/26.json"}}, "type": "issue", "id": 26, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "mzXML reader"}, "content": {"raw": "Since it returned something with `id='19'` rather than `num='19'`, I suspect that you are using the parser which defaults to `'id'` as the scan ID key. That would be the case if you are using the latest release version, as opposed to the development version of pyteomics. This issue was discussed [on our mailing list](https://groups.google.com/forum/#!topic/pyteomics/MbCNisVtq4Q), and unfortunately there hasn't been a new release since then.\n\nIf that is the case, you should be able to get the correct result by explicitly specifying `'num'` as the ID key:\n\n\n```\n#!python\n\nf.get_by_id('19', 'num')\n```\n\n... or by installing the latest pyteomics version from the repository.\n\nIf neither of those help, please share the example file and we'll look into the problem.", "markup": "markdown", "html": "<p>Since it returned something with <code>id='19'</code> rather than <code>num='19'</code>, I suspect that you are using the parser which defaults to <code>'id'</code> as the scan ID key. That would be the case if you are using the latest release version, as opposed to the development version of pyteomics. This issue was discussed <a data-is-external-link=\"true\" href=\"https://groups.google.com/forum/#!topic/pyteomics/MbCNisVtq4Q\" rel=\"nofollow\">on our mailing list</a>, and unfortunately there hasn't been a new release since then.</p>\n<p>If that is the case, you should be able to get the correct result by explicitly specifying <code>'num'</code> as the ID key:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"n\">f</span><span class=\"o\">.</span><span class=\"n\">get_by_id</span><span class=\"p\">(</span><span class=\"s1\">&#39;19&#39;</span><span class=\"p\">,</span> <span class=\"s1\">&#39;num&#39;</span><span class=\"p\">)</span>\n</pre></div>\n\n\n<p>... or by installing the latest pyteomics version from the repository.</p>\n<p>If neither of those help, please share the example file and we'll look into the problem.</p>", "type": "rendered"}, "created_on": "2018-05-09T22:28:36.368556+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 45343727}